import Nav from '@/Components/Nav'
import './globals.css'
import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import Nav2 from '@/Components/Nav2'
import Nav3 from '@/Components/Nav3'

const inter = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Americana Restaurant - Las Vegas, NV',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Nav /> */}
        <Nav3 />
        {children}
        <div className='md:hidden'>
          <Nav2 />
        </div>
      </body>
    </html>
  )
}
